id: P010376
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 20:46:40.185460
source_metadata:
  id: bdr:W3CN7651
  title: འཕགས་པ་ཤེས་རབ་ཀྱི་ཕ་རོལ་དུ་ཕྱིན་པ་བརྒྱད་སྟོང་པ།
  author: ''
  volumes:
    eb9fd6fe84544a8e83f13b32708c4358:
      image_group_id: I3CN7653
      title: ''
      volume_number: 1
      total_pages: 1157
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
